# Generated by Django 5.2.3 on 2025-06-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='registered_event',
            field=models.ManyToManyField(related_name='registered_event', to='events.event'),
        ),
    ]
