# Generated by Django 5.2.3 on 2025-06-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_date_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('SELECT CATEGORY', 'Not Mentioned'), ('SPORTS', 'Sports'), ('FESTIVAL', 'Festival'), ('SEMINAR', 'Seminar')], default='SELECT CATEGORY', max_length=50),
        ),
    ]
