# Generated by Django 5.2.3 on 2025-06-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('SELECT CATEGORY', 'Select Category'), ('SPORTS', 'Sports'), ('FESTIVAL', 'Festival'), ('SEMINAR', 'Seminar')], default='SELECT CATEGORY', max_length=50),
        ),
    ]
