# Generated by Django 5.2.3 on 2025-06-30 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='category_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
