# Generated by Django 5.2.3 on 2025-06-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_description_category_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
